name: Snake
on:
  schedule:
    - cron: "0 23 * * *" # jalan tiap hari (±06:00 WIB)
  workflow_dispatch:      # bisa dijalankan manual dari tab Actions
  push:
    branches: ["main"]    # sesuaikan kalau default branch kamu bukan main

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: alifanLeywin
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output     # hasil SVG disimpan di branch "output"
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
